SVGPath에 따라 선이 그려지는 기능 추가
golangkorea/gophercon-korea-web pull request #35
Opened 2024-09-15 15:20 UTC by wooseok123

### svg path에 따라 선이 그려지며, 비행기가 붙어서 가는 기능을 구현했습니다.

위 사항 관련 특이점들은 다음과 같습니다.

1) 점선 구현 실패

stroke-dash-offset 과 stroke-dash-array 가 svg animation 구현의 주된 속성인데,
stroke-dash-array가 path의 length 만큼 차지하는 상태에서, offset 값만큰 뺴면서 구현하기에,
실선으로 밖에 구현하지 못했습니다.

2) 비행기 구현

선에 따라 각도를 타고 이동하는 로직을 개발했습니다. 다만 시작 지점부터 선이 나와 있어야 비행기 위치 고정이 가능할 듯 합니다.
(지금은 시작 지점부터 선이 내려감)

3) fallback 화면 추가 필요

client 로직이 추가됨에 따라, 페이지가 첫 로딩되는 시점 - js가 실행되는 시점의 간극으로 인해 svg path 로직이 뒤늦게 작동되고 있습니다. 이에 모든 client 관련 로직이 작동되기 전까지, fallback screen을 띄워 주는 것이 ux상 괜찮을 듯 합니다

2024-09-15 15:23 UTC, wooseok123 commented on apps/gophercon-korea-web-24/src/components/AirplaneSVG/index.tsx
> +          airplaneRef.current.style.transform = `translate(${currentPoint.x - 1290}px, ${currentPoint.y - 25}px) rotate(${angle}deg)`;
1290px이라고 되어 있는 부분은 현재 Image가 위치된 기점으로 이만큼의 offset을 빼줘야 해당 path로 자리잡아서 이렇게 해두었지만, 이후 적절한 값을 넣어주어야 할 듯 합니다.

2024-09-19 18:29 UTC, KennethanCeyer commented on apps/gophercon-korea-web-24/src/components/AirplaneSVG/index.tsx
> +          airplaneRef.current.style.transform = `translate(${currentPoint.x - 1290}px, ${currentPoint.y - 25}px) rotate(${angle}deg)`;
이 부분 반응형 적용된 버전으로 Follow up PR 부탁드립니다.

2024-09-19 18:29 UTC, KennethanCeyer requested changes
Image는 PNG가 아닌 SVG로 추출해서 사용부탁드려요

2024-09-20 06:06 UTC, wooseok123 commented on apps/gophercon-korea-web-24/src/components/AirplaneSVG/index.tsx
> +          airplaneRef.current.style.transform = `translate(${currentPoint.x - 1290}px, ${currentPoint.y - 25}px) rotate(${angle}deg)`;
넵 확인해보겠습니다

2024-09-20 06:07 UTC, wooseok123 commented
> Image는 PNG가 아닌 SVG로 추출해서 사용부탁드려요

svg로 진행하는 특별한 이유가 있을까요?? (화질?)

2024-09-28 15:57 UTC, merged